name: graphlayoutlm 
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.7
  - numpy
  - pywin32
  - cudatoolkit=11.0
  - pytorch==1.10.0
  - torchvision==0.11.1
  - git
  - pip
  - pip:
    - git+https://github.com/facebookresearch/detectron2.git