name: graphlayoutlm 
channels:
  - pytorch
  - conda-forge
  - nvidia
  - anaconda
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pywin32
  - cudatoolkit=11.8
  - pytorch=2.1.0
  - torchvision==0.16.0
  - git
  - pip
  - pip:
    - git+https://github.com/facebookresearch/detectron2.git
    - accelerate==0.18.0
    - setuptools==58.0.4
    - datasets==2.16.1
    - transformers==4.28.1
    - timm==0.4.12
    - seqeval==1.2.2
    - shapely==2.0.2